server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: bigmall-auth #路由的ID
          uri: lb://bigmall-auth #匹配后路由地址  lb://是指当前注册中心下  后面的是微服务的名字
          predicates: # 断言，路径相匹配的进行路由
            - Path=/bigmall-auth/**
          filters:
            - StripPrefix=1
        - id: bigmall-admin
          uri: lb://bigmall-admin
          predicates:
            - Path=/bigmall-admin/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/bigmall-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 47.99.113.23 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/bigmall-auth/oauth/token"
      - "/bigmall-auth/rsa/publicKey"
      - "/bigmall-admin/admin/login"
      - "/bigmall-admin/admin/register"
      - "/bigmall-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
