server:
  port: 8401
management:
  endpoints:
    web:
      exposure:
        include: "*"
#添加log日志
logging:
  file:
    path: D:\Log
  level:
    root: info
    com.xcm.bigmall: debug
logstash:
  host: 47.99.113.23
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
